/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.JogoVO;
import servicos.JogoServicos;
import servicos.ServicosFactory;

/**
 * @author Thiago Cury
 * @since 25/04/2014
 * @version 1.0
 */
public class GuiManutencaoJogo extends javax.swing.JInternalFrame {

    DefaultTableModel dtm = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"Código", "Nome", "Empresa"});

    /**
     * Creates new form GuiManutencaoSeriado
     */
    public GuiManutencaoJogo() {
        initComponents();
        
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtableJogo = new javax.swing.JTable();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jbBuscar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbDeletar = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jtPesquisa = new javax.swing.JTextField();
        jcbFiltro = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setTitle("manutenção de jogos");
        setToolTipText("");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtableJogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtableJogo.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jtableJogo);

        jLayeredPane1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 20, 430, 230);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jbBuscar);
        jbBuscar.setBounds(20, 12, 100, 50);

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jbLimpar);
        jbLimpar.setBounds(130, 12, 100, 50);

        jbDeletar.setText("Deletar");
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jbDeletar);
        jbDeletar.setBounds(240, 12, 210, 50);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesquisaKeyReleased(evt);
            }
        });

        jcbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Código", "Empresa" }));
        jcbFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbFiltroItemStateChanged(evt);
            }
        });

        jLayeredPane3.setLayer(jtPesquisa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jcbFiltro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jcbFiltro)
                    .addComponent(jtPesquisa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1)
                    .addComponent(jLayeredPane3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preencherTabela() {
        try {
            ArrayList<JogoVO> jogos = new ArrayList<>();
            JogoServicos js = ServicosFactory.getJogoServicos();
            jogos = js.buscarJogos();

            limparTabela();
            
            for (int i = 0; i < jogos.size(); i++) {
                dtm.addRow(new String[]{
                    String.valueOf(jogos.get(i).getIdJogo()),
                    jogos.get(i).getNome(),
                    jogos.get(i).getEmpresa()
                });
            }
            jtableJogo.setModel(dtm);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro! " + e.getMessage());
        }
    }

    private void limparTabela() {
        dtm.setNumRows(0);
    }
    
    private void filtrar() {
        try {
            if (jtPesquisa.getText().isEmpty()) {
                limparTabela();
                preencherTabela();
                return;
            }
            
            String pesquisa = jtPesquisa.getText();
            String filtro = jcbFiltro.getSelectedItem().toString();
            JogoServicos js = ServicosFactory.getJogoServicos();
            ArrayList<JogoVO> prods = js.filtrar(pesquisa, filtro);
            
            for(int i=0 ; i<prods.size() ; i++) {
                dtm.addRow(new String[]{
                    String.valueOf(prods.get(i).getIdJogo()),
                    prods.get(i).getNome(),
                    prods.get(i).getEmpresa(),
                });
            }
            
            /* Adicionando o modelo de tabela 
             com os dados na tabela produto */
            jtableJogo.setModel(dtm);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro!" +e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }//fecha catch
    }//fecha filtrar
    
    private void deletar() {
        try {
            int linha = jtableJogo.getSelectedRow();
            if (linha == -1) {
                JOptionPane.showMessageDialog(this, "selecione uma linha para excluir!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }//fecha if
            
            String id = jtableJogo.getValueAt(linha, 0).toString();
            
            JogoServicos js = ServicosFactory.getJogoServicos();
            js.deletarJogo(Long.parseLong(id));
            
            JOptionPane.showMessageDialog(this, "Jogo excluído com sucesso!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro!" +e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//fecha deletar

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limparTabela();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesquisaKeyReleased
        limparTabela();
        filtrar();
    }//GEN-LAST:event_jtPesquisaKeyReleased

    private void jcbFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbFiltroItemStateChanged
        limparTabela();
        filtrar();
    }//GEN-LAST:event_jcbFiltroItemStateChanged

    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed
        deletar();
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbDeletarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JComboBox<String> jcbFiltro;
    private javax.swing.JTextField jtPesquisa;
    private javax.swing.JTable jtableJogo;
    // End of variables declaration//GEN-END:variables
}
